import type { Metadata } from "next";
import { Baloo_2, Nunito } from "next/font/google";
import "katex/dist/katex.min.css";
import "./globals.css";

const nunito = Nunito({
  weight: "variable",
  variable: "--font-nunito",
  subsets: ["latin", "vietnamese"],
  display: "swap",
});

const baloo = Baloo_2({
  weight: "variable",
  variable: "--font-baloo",
  subsets: ["latin", "vietnamese"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="vi"
      className={`${nunito.variable} ${baloo.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
